# What standard to use. This is optional and defaults to VHDL2008.
standard = "2008"
# File names are either absolute or relative to the parent folder of the vhdl_ls.toml file
[libraries]
src.files = [
    'src/*.vhd',
    'src/**/*.vhd',
]
test.files = [
    #'src/**/*.vhd',
    'test/*/*.vhd',
    'test/*.vhd'
]
# lib3.exclude = [
#     'test/*_old.vhd',
# ]

# Libraries can be marked as third-party to disable some analysis warnings, such as unused declarations
#VUNIT.files = ['.venv/lib/python3.10/site-packages/vunit/vhdl/**/*.vhd', '.venv/lib/python3.10/site-packages/vunit/vhdl/*.vhd']
#VUNIT.is_third_party = true

[lint]
unused = 'warning' # Upgrade the 'unused' diagnostic to the 'warning' severity
unnecessary_work_library = false # Disable linting for the 'library work;' statement